all:
  vars:
    validator_user: sol
    solana_version: v1.4.9
    run_validator: true
    nginx_sites:
      - validator.conf

load_balancers:
  hosts:
    validator-load-balancer-standard.test.net:
      extra_packages:
        - nginx
    validator-load-balancer-health-checks.test.net:
      nginx_sites:
        - validator-health-checks.conf
        - dashboard.conf
  vars:
    is_watchtower: true
    etc_dir: lb
    run_validator: false

validators:
  hosts:
    validator-1.test.net:
    validator-2.test.net:
  vars:
    etc_dir: validator
    supervisord_conf_file: validator.conf
    # Uncomment below to specify a location other than the root device to store ledger data. One use case would be
    # for a higher bandwidth drive than the root device, which may be a network drive.
    # local_disk: /dev/nvme1n1
    extra_packages:
      - nginx
